# Generated by Django 5.2.7 on 2025-12-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(max_length=300)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
