# Generated by Django 5.2.7 on 2025-12-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='titulo',
        ),
    ]
