# Generated by Django 5.2.7 on 2025-12-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_noticia_resumo_remove_noticia_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
